{ "name" :"Leon",
"dept" :"Alefloat engineering",
"post" :"Manager",
"salary" :32014,
"status" :"permanent" },
{ "name" :"Lorena",
"dept" :"Research",
"post" :"Manager",
"salary" :33124,
"status" :"permanent" },
{ "name" :"Nikolas",
"dept" :"Business",
"post" :"Director",
"salary" :310094,
"status" :"permanent" }